### PR TITLE
Signal regex

### PR DESCRIPTION
**Pull request by Murmele**
- signals can also contain special characters: SG_ SPEED : 0|8@1+ (1,0) [0|204] "Km/h"  DEVICE1,DEVICE2,DEVICE3
- multiple whitespaces at the end:  SG_ TEMPERATURE : 48|16@1+ (0.01,-40) [-40|125] "C"  DEVICE1,DEVICE2,DEVICE3

It seems to be that the second case will be also parsed without the +, but I don't understand why, maybe you have an idea

### CODE REVIEW

**Comment by Murmele** [comment]
I did not find any documentation about the dbc which describes which characters are allowed and which not

**Comment by LinuxDevon** [comment]
I think this was my original reference used (http://mcu.so/Microcontroller/Automotive/dbc-file-format-documentation_compress.pdf). The standard isn't really well defined and sort of custom sometimes I have found. 

I did / still do use the https://pypi.org/project/cantools/ as a reference for how they parse DBC files.

**Comment by Murmele** [comment]
Ah cool I searched for something like this, but indeed there is nothing which characters are allowed and which not.

**Comment by Murmele** [comment]
merged into #9

**Pull request closed without merging**
