### PR TITLE
minimum and maximum value can also be negative values

### PR DESCRIPTION
**Pull request by Murmele**
Example:

```
BO_ 234 MSG1: 8 Vector__XXX
 SG_ Sig1 : 55|16@0- (0.1,0) [-3276.8|3276.7] "C" Vector__XXX
 SG_ Sig2 : 39|16@0- (0.1,0) [-3276.8|3276.7] "C" Vector__XXX
 SG_ Sig3 : 23|16@0- (0.1,0) [-3276.8|3276.7] "C" Vector__XXX
 SG_ Sig4 : 7|16@0- (1,0) [0|32767] "" Vector__XXX
```

### CODE REVIEW

**Comment by Murmele** [comment]
@LinuxDevon

**Comment by LinuxDevon** [comment]
@Murmele looks good and thank you! 
Looking over that string I should really change those to [raw strings](https://en.cppreference.com/w/cpp/language/string_literal) to make it look cleaner.

**Review by LinuxDevon — APPROVED** [review]

**Comment by Murmele** [comment]
> @Murmele looks good and thank you! Looking over that string I should really change those to [raw strings](https://en.cppreference.com/w/cpp/language/string_literal) to make it look cleaner.

Yes maybe splitting up and the concatenating to one const string. I think the compiler will optimize it out then

**Comment by Murmele** [comment]
@LinuxDevon if it is fine for you, I can do that because I found at least one more issues

**Comment by LinuxDevon** [comment]
@Murmele that is fine with me. Appreciate the help! I am planning on adding in an action to run the test suite on PR. If you don't mind can you add some more edge case test for those?

**Comment by Murmele** [comment]
> 

@LinuxDevon perfect I will create some tests next days

**Pull request merged**
