### PR TITLE
Parse non byte aligned number

### PR DESCRIPTION
**Pull request by Murmele**
- [x] #14 merged

### CODE REVIEW

**Comment by LinuxDevon** [comment]
@Murmele do you need this in the release before I make it?

**Comment by Murmele** [comment]
Yes please :)

**Comment by Murmele** [comment]
I will rebase it, then you can merge it.

**Comment by Murmele** [comment]
I tested with labplot and it looks good! Thanks for merging!

**Review by LinuxDevon — APPROVED** [review]
Appreciate the work here! Appologize for the delay again. I think the release flow is broken so I will just give it a tag for now and work on an official release when I get some time and motivation.

**Comment by Murmele** [comment]
@LinuxDevon don't worry. Thanks for merging! I will update in Labplot to your release 😊

**Pull request merged**
